DROP DATABASE IF EXISTS AVIACAO;
CREATE DATABASE AVIACAO;
USE AVIACAO;

-- CLIENTE
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name = 'Clientes')
CREATE TABLE CLIENTE(
	ID_CLIENTE INT NOT NULL  PRIMARY KEY,
    NOME TEXT NOT NULL,
    CONTATO TEXT NOT NULL,
    GENERO TEXT NOT NULL,
    DATA_NASCIMENTO DATETIME NOT NULL
);


-- AEROPORTO
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name = 'Aeroporto')
CREATE TABLE AEROPORTO(
	ID_AEROPORTO INT NOT NULL  PRIMARY KEY,
    LOCALIZACAO TEXT NOT NULL
);


-- AERONAVE
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name = 'Aeronave')
CREATE TABLE TIPO_AERONAVE(
	ID_TIPO_AERONAVE INT NOT NULL  PRIMARY KEY,
	DESCRICAO TEXT NOT NULL
);
CREATE TABLE AERONAVE(
	ID_AERONAVE INT NOT NULL  PRIMARY KEY,
    QTD_POLTRONAS INT NOT NULL,
    ID_TIPO_AERONAVE INT NOT NULL,
    CONSTRAINT FK_ID_TIPO_AERONAVE FOREIGN KEY(ID_TIPO_AERONAVE) REFERENCES TIPO_AERONAVE(ID_TIPO_AERONAVE)
);

-- VOO
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name = '')
CREATE TABLE VOO(
	ID_VOO INT NOT NULL PRIMARY KEY,
    HORARIO_SAIDA DATETIME NOT NULL,
    HORARIO_DESTINO DATETIME NOT NULL,
    ID_AEROPORTO_SAIDA INT NOT NULL,
    ID_AEROPORTO_DESTINO INT NOT NULL,
    ID_AERONAVE INT NOT NULL,
    CONSTRAINT FK_ID_AEROPORTO_SAIDA_VOO FOREIGN KEY(ID_AEROPORTO_SAIDA) REFERENCES AEROPORTO(ID_AEROPORTO),
    CONSTRAINT FK_ID_AEROPORTO_DESTINO FOREIGN KEY(ID_AEROPORTO_DESTINO) REFERENCES AEROPORTO(ID_AEROPORTO),
    CONSTRAINT FK_ID_AERONAVE_VOO FOREIGN KEY(ID_AERONAVE) REFERENCES AERONAVE(ID_AERONAVE)
);

-- ESCALA
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name = '')
CREATE TABLE ESCALA(
	ID_ESCALA INT NOT NULL PRIMARY KEY,
    HORARIO_SAIDA DATETIME NOT NULL,
    ID_VOO INT NOT NULL,
    ID_AEROPORTO_SAIDA INT NOT NULL,
    CONSTRAINT FK_ID_VOO_ESCALA FOREIGN KEY(ID_VOO) REFERENCES VOO(ID_VOO),
    CONSTRAINT FK_ID_AEROPORTO_SAIDA_ESCALA FOREIGN KEY(ID_AEROPORTO_SAIDA) REFERENCES AEROPORTO(ID_AEROPORTO)
);


-- HORARIO E COMPRA
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name = '')
CREATE TABLE HORARIO(
	ID_HORARIO INT NOT NULL PRIMARY KEY,
    DISPONIBILIDADE BOOL DEFAULT TRUE,
    LADO_POLTRONA TEXT NOT NULL,
    LOCALIZACAO_POLTRONA TEXT NOT NULL,
    ID_VOO INT NOT NULL,
    CONSTRAINT FK_ID_VOO_HORARIO FOREIGN KEY(ID_VOO) REFERENCES VOO(ID_VOO)
);

CREATE TABLE COMPRA(
	ID_COMPRA INT NOT NULL PRIMARY KEY,
    ID_HORARIO INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    CONSTRAINT FK_ID_HORARIO FOREIGN KEY(ID_CLIENTE) REFERENCES HORARIO(ID_HORARIO),
    CONSTRAINT FK_ID_CLIENTE FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);